ALTER TABLE fornecedores
ADD COLUMN IF NOT EXISTS cep VARCHAR(20);

ALTER TABLE fornecedores
ADD COLUMN IF NOT EXISTS logradouro VARCHAR(180);

ALTER TABLE fornecedores
ADD COLUMN IF NOT EXISTS bairro VARCHAR(120);

ALTER TABLE fornecedores
ADD COLUMN IF NOT EXISTS uf VARCHAR(2);

ALTER TABLE fornecedores
ADD COLUMN IF NOT EXISTS complemento VARCHAR(180);